apiVersion: v1
kind: Service
metadata:
  name: cluster-manager
  namespace: gpu
  labels:
    name: cluster-manager
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 8686
    protocol: TCP
  selector:
    name: cluster-manager